"""Test-only synthetic apparatus for externally downloaded execution bundles.

These fixed fixtures generate acceptance-test evidence. They are not registered
product models, execution providers, or physical-hardware interfaces.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import os
import tempfile
import zipfile
from collections.abc import Mapping, Sequence
from dataclasses import replace
from pathlib import Path, PurePosixPath
from typing import Any

import numpy as np

from cfdc.kernel.contracts import fingerprint
from cfdc.sim.execution import LinearPlant, simulate_trial

RUNNER_ID = "synthetic_test_fixture"
RUNNER_VERSION = "external-synthetic/v1"
_CAPABILITIES = (
    "software_only",
    "siso",
    "identification_csv",
    "evaluation_trace_zip",
    "deterministic_trial_resume",
)
_TRANSFERS = {
    "optical": ([1.6], [1.1, 1.0]),
    "vacuum": ([-1.4], [1.3, 1.0]),
    "ink": ([-1.8], [0.75, 2.0, 1.0]),
}
_INPUT_DELAYS_S = {"optical": 0.0, "vacuum": 0.4, "ink": 0.0}


def _model_binding(model_id: str) -> dict[str, Any]:
    if model_id not in _TRANSFERS:
        raise ValueError("synthetic_model_unknown")
    value = {
        "runner_id": RUNNER_ID,
        "runner_version": RUNNER_VERSION,
        "model_id": model_id,
        "model_version": "1.0.0",
        "capabilities": list(_CAPABILITIES),
    }
    # Bind test checkpoints to fixture dynamics so changed fixtures cannot
    # reuse results generated by an earlier definition.
    numerator, denominator = _TRANSFERS[model_id]
    value["model_fingerprint"] = fingerprint(
        {
            **value,
            "private_definition": {
                "numerator": list(numerator),
                "denominator": list(denominator),
                "input_delay_s": _INPUT_DELAYS_S[model_id],
            },
        }
    )
    return value


def catalog() -> list[dict[str, Any]]:
    """Return the complete test-fixture catalog."""
    return [_model_binding(model_id) for model_id in _TRANSFERS]


def binding(model_id: str) -> dict[str, Any]:
    """Return an immutable-value description of one test fixture."""
    return _model_binding(model_id)


def _names(task: Mapping[str, Any], plural: str, singular: str) -> tuple[str, ...]:
    raw = task.get(plural)
    if raw is None:
        raw = task.get(singular)
    if isinstance(raw, str):
        raw = [raw]
    if not isinstance(raw, Sequence) or isinstance(raw, (bytes, bytearray)):
        return ()
    return tuple(str(item).strip() for item in raw if str(item).strip())


def validate_task(model_id: str, task: Mapping[str, Any]) -> None:
    """Validate model selection and the SISO interface without renaming channels."""
    _model_binding(model_id)
    inputs = _names(task, "control_inputs", "control_input")
    outputs = _names(task, "measured_signals", "output_signal")
    if len(inputs) != 1 or len(outputs) != 1:
        raise ValueError("synthetic_model_requires_siso")


def apparatus(kind: str, inputs: Sequence[str], outputs: Sequence[str]) -> LinearPlant:
    """Create the selected fixed plant with the caller's exact channel names."""
    _model_binding(kind)
    input_names = tuple(inputs)
    output_names = tuple(outputs)
    validate_task(
        kind, {"control_inputs": input_names, "measured_signals": output_names}
    )
    transfer = _TRANSFERS[kind]
    return LinearPlant.from_transfer_matrix(
        [[transfer]],
        inputs=input_names,
        outputs=output_names,
        delays={input_names[0]: _INPUT_DELAYS_S[kind]} if _INPUT_DELAYS_S[kind] else {},
    )


def _bundle_sha256(bundle: Path) -> str:
    digest = hashlib.sha256()
    with bundle.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _safe_archive(archive: zipfile.ZipFile) -> set[str]:
    infos = archive.infolist()
    names = [item.filename for item in infos]
    if (
        len(names) != len(set(names))
        or len(names) > 10_002
        or sum(item.file_size for item in infos) > 100_000_000
        or any(
            PurePosixPath(name).is_absolute() or ".." in PurePosixPath(name).parts
            for name in names
        )
    ):
        raise ValueError("synthetic_bundle_invalid")
    return set(names)


def _bundle_description(
    bundle: Path,
) -> tuple[str, dict[str, Any], list[dict[str, str]]]:
    try:
        with zipfile.ZipFile(bundle) as archive:
            names = _safe_archive(archive)
            if "operator_card.json" in names:
                card = json.loads(archive.read("operator_card.json"))
                csv_names = sorted(name for name in names if name.endswith(".csv"))
                trials = [
                    {
                        "trial_id": PurePosixPath(name).name,
                        "file": PurePosixPath(name).name,
                    }
                    for name in csv_names
                ]
                validate_task(
                    "optical",
                    {
                        "control_inputs": card.get("control_inputs"),
                        "measured_signals": card.get("requested_signals"),
                    },
                )
                if not trials or len({row["trial_id"] for row in trials}) != len(
                    trials
                ):
                    raise ValueError("synthetic_bundle_trials_required")
                return (
                    "identification",
                    {
                        "card": card,
                        "sources": dict(
                            zip(
                                (row["trial_id"] for row in trials),
                                csv_names,
                                strict=True,
                            )
                        ),
                    },
                    trials,
                )
            if {"execution-request.json", "manifest.json"} <= names:
                request = json.loads(archive.read("execution-request.json"))
                manifest = json.loads(archive.read("manifest.json"))
                validate_task(
                    "optical",
                    {
                        "control_inputs": request.get("control_inputs"),
                        "measured_signals": request.get("measured_signals"),
                    },
                )
                manifest_trials = manifest.get("trials")
                request_trials = request.get("trials")
                if not isinstance(manifest_trials, list) or not isinstance(
                    request_trials, list
                ):
                    raise ValueError("synthetic_bundle_trials_required")
                request_ids = [str(row.get("trial_id", "")) for row in request_trials]
                trials = []
                for row in manifest_trials:
                    trial_id, filename = (
                        str(row.get("trial_id", "")),
                        str(row.get("file", "")),
                    )
                    if (
                        not trial_id
                        or request_ids.count(trial_id) != 1
                        or not filename
                        or Path(filename).name != filename
                        or filename in names
                    ):
                        raise ValueError("synthetic_bundle_trial_binding_invalid")
                    trials.append({"trial_id": trial_id, "file": filename})
                if not trials or len({row["trial_id"] for row in trials}) != len(
                    trials
                ):
                    raise ValueError("synthetic_bundle_trials_required")
                return "evaluation", {"request": request, "manifest": manifest}, trials
    except (OSError, zipfile.BadZipFile, KeyError, json.JSONDecodeError) as exc:
        raise ValueError("synthetic_bundle_invalid") from exc
    raise ValueError("synthetic_bundle_kind_unknown")


def bundle_trials(bundle: Path) -> list[str]:
    return [row["trial_id"] for row in _bundle_description(Path(bundle))[2]]


def _checkpoint_binding(
    bundle: Path, model_id: str, trial_id: str, filename: str
) -> dict[str, Any]:
    value = {
        "runner": binding(model_id),
        "bundle_sha256": _bundle_sha256(bundle),
        "trial_id": trial_id,
        "output_filename": filename,
    }
    value["binding_fingerprint"] = fingerprint(value)
    return value


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _install_new(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        try:
            os.link(temporary, path)
        except FileExistsError as exc:
            raise ValueError("synthetic_checkpoint_conflict") from exc
    finally:
        Path(temporary).unlink(missing_ok=True)


def _trial_payload(
    bundle: Path,
    kind: str,
    description: Mapping[str, Any],
    trial_id: str,
    model_id: str,
) -> bytes:
    with zipfile.ZipFile(bundle) as archive:
        if kind == "identification":
            card = description["card"]
            reader = csv.DictReader(
                io.StringIO(
                    archive.read(description["sources"][trial_id]).decode("utf-8-sig")
                )
            )
            if reader.fieldnames is None:
                raise ValueError("synthetic_identification_csv_invalid")
            plant = apparatus(
                model_id, card["control_inputs"], card["requested_signals"]
            )
            output = io.StringIO(newline="")
            writer = csv.DictWriter(output, fieldnames=reader.fieldnames)
            writer.writeheader()
            input_name = card["control_inputs"][0]
            for row in reader:
                for name in card["requested_signals"]:
                    row[name] = f"{plant.measure()[name]:.12g}"
                writer.writerow(row)
                plant.advance(
                    {input_name: float(row[input_name])}, float(card["sample_period_s"])
                )
            return output.getvalue().encode()
        request = description["request"]
        scenario = next(row for row in request["trials"] if row["trial_id"] == trial_id)
        plant = apparatus(
            model_id, request["control_inputs"], request["measured_signals"]
        )
        plant = replace(
            plant,
            initial_state=np.random.default_rng(scenario["seed"]).uniform(
                -1e-6, 1e-6, plant.a.shape[0]
            ),
        )
        return json.dumps(simulate_trial(request, scenario, plant)).encode()


def execute_trial(
    bundle: Path, output_dir: Path, model_id: str, trial_id: str
) -> dict[str, Any]:
    bundle, output_dir = Path(bundle), Path(output_dir)
    kind, description, trials = _bundle_description(bundle)
    binding(model_id)
    matches = [row for row in trials if row["trial_id"] == trial_id]
    if len(matches) != 1:
        raise ValueError("synthetic_trial_unknown")
    filename = matches[0]["file"]
    checkpoint = _checkpoint_binding(bundle, model_id, trial_id, filename)
    output_path = output_dir / filename
    marker_path = output_dir / f"{filename}.completed.json"
    if output_path.exists() and not marker_path.exists():
        payload = _trial_payload(bundle, kind, description, trial_id, model_id)
        if output_path.read_bytes() != payload:
            raise ValueError("synthetic_checkpoint_conflict")
        result = {
            "status": "completed",
            "runner_id": RUNNER_ID,
            "model_id": model_id,
            "trial_id": trial_id,
            "output_filename": filename,
            "output_sha256": _sha256(payload),
            "binding_fingerprint": checkpoint["binding_fingerprint"],
            "reused": False,
            "recovered": True,
        }
        marker = {
            "binding": checkpoint,
            "output_sha256": result["output_sha256"],
            "result": result,
        }
        _install_new(marker_path, (json.dumps(marker, sort_keys=True) + "\n").encode())
        return result
    if output_path.exists() or marker_path.exists():
        try:
            marker = json.loads(marker_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError("synthetic_checkpoint_conflict") from exc
        if marker.get("binding") != checkpoint or marker.get(
            "output_sha256"
        ) != _sha256(output_path.read_bytes()):
            raise ValueError("synthetic_checkpoint_conflict")
        return {**marker["result"], "reused": True}
    payload = _trial_payload(bundle, kind, description, trial_id, model_id)
    result = {
        "status": "completed",
        "runner_id": RUNNER_ID,
        "model_id": model_id,
        "trial_id": trial_id,
        "output_filename": filename,
        "output_sha256": _sha256(payload),
        "binding_fingerprint": checkpoint["binding_fingerprint"],
        "reused": False,
    }
    marker = {
        "binding": checkpoint,
        "output_sha256": result["output_sha256"],
        "result": result,
    }
    _install_new(output_path, payload)
    try:
        _install_new(marker_path, (json.dumps(marker, sort_keys=True) + "\n").encode())
    except Exception:
        output_path.unlink(missing_ok=True)
        raise
    return result


def assemble_results(bundle: Path, output_dir: Path, result_path: Path) -> Path:
    bundle, output_dir, result_path = Path(bundle), Path(output_dir), Path(result_path)
    kind, description, trials = _bundle_description(bundle)
    payloads: list[tuple[str, bytes]] = []
    for row in trials:
        path = output_dir / row["file"]
        marker_path = output_dir / f"{row['file']}.completed.json"
        try:
            marker = json.loads(marker_path.read_text(encoding="utf-8"))
            payload = path.read_bytes()
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError("synthetic_checkpoint_incomplete") from exc
        if marker.get("output_sha256") != _sha256(payload):
            raise ValueError("synthetic_checkpoint_conflict")
        payloads.append((row["file"], payload))
    if kind == "identification":
        result_path.mkdir(parents=True, exist_ok=True)
        for filename, payload in payloads:
            destination = result_path / filename
            if destination.exists() and destination.read_bytes() != payload:
                raise ValueError("synthetic_result_conflict")
            if not destination.exists():
                _install_new(destination, payload)
        return result_path
    result_path.parent.mkdir(parents=True, exist_ok=True)
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        members = [("manifest.json", json.dumps(description["manifest"]).encode())]
        members.extend(payloads)
        for filename, payload in members:
            info = zipfile.ZipInfo(filename, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o600 << 16
            archive.writestr(info, payload)
    result_payload = stream.getvalue()
    if result_path.exists():
        if result_path.read_bytes() != result_payload:
            raise ValueError("synthetic_result_conflict")
        return result_path
    _install_new(result_path, result_payload)
    return result_path


def identify(archive: zipfile.ZipFile, output: Path, kind: str) -> None:
    """Generate test evidence for the legacy positional CLI."""
    card = json.loads(archive.read("operator_card.json"))
    output.mkdir(parents=True, exist_ok=True)
    for filename in sorted(
        name for name in archive.namelist() if name.endswith(".csv")
    ):
        payload = _trial_payload_from_archive(archive, card, filename, kind)
        (output / Path(filename).name).write_bytes(payload)


def _trial_payload_from_archive(archive, card, filename, kind):
    reader = csv.DictReader(io.StringIO(archive.read(filename).decode("utf-8-sig")))
    plant = apparatus(kind, card["control_inputs"], card["requested_signals"])
    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=reader.fieldnames)
    writer.writeheader()
    for row in reader:
        for name in card["requested_signals"]:
            row[name] = f"{plant.measure()[name]:.12g}"
        writer.writerow(row)
        plant.advance(
            {card["control_inputs"][0]: float(row[card["control_inputs"][0]])},
            card["sample_period_s"],
        )
    return stream.getvalue().encode()


def evaluate(archive: zipfile.ZipFile, output: Path, kind: str) -> None:
    """Generate test evidence for the legacy positional CLI."""
    request = json.loads(archive.read("execution-request.json"))
    manifest = json.loads(archive.read("manifest.json"))
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as result:
        result.writestr("manifest.json", json.dumps(manifest))
        for scenario, row in zip(request["trials"], manifest["trials"], strict=True):
            plant = apparatus(
                kind, request["control_inputs"], request["measured_signals"]
            )
            plant = replace(
                plant,
                initial_state=np.random.default_rng(scenario["seed"]).uniform(
                    -1e-6, 1e-6, plant.a.shape[0]
                ),
            )
            result.writestr(
                row["file"], json.dumps(simulate_trial(request, scenario, plant))
            )


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("bundle", nargs="?", type=Path)
    parser.add_argument("output", nargs="?", type=Path)
    parser.add_argument("--plant", choices=tuple(_TRANSFERS), default="optical")
    parser.add_argument("--bundle", dest="trial_bundle", type=Path)
    parser.add_argument("--output-dir", "--output", dest="output_dir", type=Path)
    parser.add_argument("--model", "--model-id", choices=tuple(_TRANSFERS))
    parser.add_argument("--trial", "--trial-id")
    args = parser.parse_args(argv)
    if args.bundle is not None:
        if args.output is None or any(
            value is not None
            for value in (args.trial_bundle, args.output_dir, args.model, args.trial)
        ):
            parser.error("provide bundle output --plant, or the single-trial flags")
        with zipfile.ZipFile(args.bundle) as archive:
            if "operator_card.json" in archive.namelist():
                identify(archive, args.output, args.plant)
            else:
                evaluate(archive, args.output, args.plant)
        return
    if args.output is not None or any(
        value is None
        for value in (args.trial_bundle, args.output_dir, args.model, args.trial)
    ):
        parser.error("single-trial mode requires --bundle --output-dir --model --trial")
    print(
        json.dumps(
            execute_trial(args.trial_bundle, args.output_dir, args.model, args.trial),
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
