/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration */
        get: operations["configuration_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe */
        post: operations["probe_api_v1_config_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Doctor */
        post: operations["doctor_api_v1_config_doctor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cases */
        get: operations["cases_api_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Case */
        get: operations["case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Draft */
        get: operations["default_draft_api_v1_drafts_default_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Draft */
        post: operations["validate_draft_api_v1_drafts_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import History */
        post: operations["import_history_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task */
        get: operations["task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action */
        post: operations["action_api_v1_tasks__task_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation */
        get: operations["operation_api_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Operations */
        get: operations["task_operations_api_v1_tasks__task_id__operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Artifact */
        post: operations["validate_artifact_api_v1_artifacts_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifacts */
        get: operations["artifacts_api_v1_tasks__task_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/artifacts/{artifact_id}/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node */
        get: operations["node_api_v1_tasks__task_id__artifacts__artifact_id__node_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/sections/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Section Page */
        get: operations["section_page_api_v1_tasks__task_id__sections__section__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/protocol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Protocol */
        get: operations["protocol_api_v1_tasks__task_id__protocol_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluations */
        get: operations["evaluations_api_v1_tasks__task_id__evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/curves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Curves */
        get: operations["curves_api_v1_tasks__task_id__curves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/evidence/curves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence Curves */
        get: operations["evidence_curves_api_v1_tasks__task_id__evidence_curves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/downloads/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_v1_tasks__task_id__downloads__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionInput */
        ActionInput: {
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Mode
             * @default natural_language
             * @enum {string}
             */
            mode: "natural_language" | "json";
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** File Ids */
            file_ids?: string[];
            /**
             * Stopped On Limit
             * @default false
             */
            stopped_on_limit: boolean;
        };
        /** ActionRequest */
        ActionRequest: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Action */
            action: string;
            input?: components["schemas"]["ActionInput"];
            credentials?: components["schemas"]["Credentials"];
        };
        /** ArtifactCatalog */
        ArtifactCatalog: {
            /** Session Id */
            session_id: string;
            /** Revision */
            revision: number;
            /** Items */
            items: components["schemas"]["CatalogItem"][];
        };
        /** ArtifactValidationRequest */
        ArtifactValidationRequest: {
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** ArtifactValidationResponse */
        ArtifactValidationResponse: {
            /**
             * Valid
             * @default true
             */
            valid: boolean;
            /** Artifact */
            artifact: {
                [key: string]: unknown;
            };
        };
        /** Body_upload_api_v1_uploads_post */
        Body_upload_api_v1_uploads_post: {
            /** File */
            file: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** CaseCard */
        CaseCard: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "engineering" | "audit";
            /** Description */
            description: string;
            /** Data Source */
            data_source: string;
            /** Scope */
            scope: string;
        };
        /** CaseDetail */
        CaseDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "engineering" | "audit";
            /** Description */
            description: string;
            /** Data Source */
            data_source: string;
            /** Scope */
            scope: string;
            /** Draft */
            draft: {
                [key: string]: unknown;
            };
            /** Task */
            task: {
                [key: string]: unknown;
            };
            /** Learning */
            learning: {
                [key: string]: unknown;
            };
        };
        /** CaseList */
        CaseList: {
            /** Items */
            items: components["schemas"]["CaseCard"][];
        };
        /** CatalogItem */
        CatalogItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Fingerprint */
            fingerprint?: string | null;
        };
        /** Column */
        Column: {
            /** Name */
            name: string;
            /** Unit */
            unit: string;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
            rag: components["schemas"]["RAGStatus"];
            /**
             * Version
             * @default 0.3.4
             */
            version: string;
        };
        /** CreateRequest */
        CreateRequest: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Draft */
            draft?: {
                [key: string]: unknown;
            } | null;
            /** Task */
            task?: {
                [key: string]: unknown;
            } | null;
            /**
             * Case Id
             * @default
             */
            case_id: string;
            /**
             * Evidence Mode
             * @default automatic
             * @enum {string}
             */
            evidence_mode: "automatic" | "exercise_bundle";
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /**
             * Use Rag
             * @default true
             */
            use_rag: boolean;
            credentials?: components["schemas"]["Credentials"];
        };
        /** Credentials */
        Credentials: {
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
        };
        /** Curve */
        Curve: {
            /** Name */
            name: string;
            /** X */
            x: number[];
            /** Y */
            y: number[];
            /** Unit */
            unit: string;
        };
        /** CurveView */
        CurveView: {
            /** Session Id */
            session_id: string;
            /** Revision */
            revision: number;
            /** Selection */
            selection: string;
            /** Signal */
            signal: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "development" | "confirmation";
            /** Fingerprint */
            fingerprint?: string | null;
            /** Selected Control */
            selected_control?: string | null;
            /** Original Points */
            original_points: number;
            /** Display Points */
            display_points: number;
            /** Output */
            output: components["schemas"]["Curve"][];
            /** Control */
            control: components["schemas"]["Curve"][];
        };
        /** DoctorCheck */
        DoctorCheck: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /** DoctorRequest */
        DoctorRequest: {
            credentials?: components["schemas"]["Credentials"];
            /**
             * Use Rag
             * @default true
             */
            use_rag: boolean;
        };
        /** DoctorResponse */
        DoctorResponse: {
            /** Checks */
            checks: components["schemas"]["DoctorCheck"][];
        };
        /** DraftRequest */
        DraftRequest: {
            /** Draft */
            draft: {
                [key: string]: unknown;
            };
            /**
             * Case Id
             * @default
             */
            case_id: string;
        };
        /** DraftResponse */
        DraftResponse: {
            /** Draft */
            draft: {
                [key: string]: unknown;
            };
        };
        /** DraftValidationResponse */
        DraftValidationResponse: {
            /** Task */
            task: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["PublicError"];
        };
        /** EvaluationOption */
        EvaluationOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Signals */
            signals: string[];
            /** Control Signals */
            control_signals: string[];
            /**
             * Stage
             * @enum {string}
             */
            stage: "development" | "confirmation";
            /** Fingerprint */
            fingerprint?: string | null;
        };
        /** EvaluationsView */
        EvaluationsView: {
            /** Session Id */
            session_id: string;
            /** Revision */
            revision: number;
            /** Options */
            options: components["schemas"]["EvaluationOption"][];
            /** Metrics */
            metrics: string[][];
            /** Selected Selection */
            selected_selection?: string | null;
            /** Selected Stage */
            selected_stage?: ("development" | "confirmation") | null;
        };
        /** EvidenceCurveView */
        EvidenceCurveView: {
            /** Session Id */
            session_id: string;
            /** Revision */
            revision: number;
            /** Selection */
            selection: string;
            /** Signal */
            signal: string;
            /**
             * Stage
             * @default evidence
             * @constant
             */
            stage: "evidence";
            /** Fingerprint */
            fingerprint?: string | null;
            /** Protocol Fingerprint */
            protocol_fingerprint: string;
            /** Trial Id */
            trial_id: string;
            /** Original Points */
            original_points: number;
            /** Display Points */
            display_points: number;
            /** Output */
            output: components["schemas"]["Curve"][];
        };
        /** EvidenceOption */
        EvidenceOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Signals */
            signals: string[];
            /** Trial Id */
            trial_id: string;
            /** Fingerprint */
            fingerprint?: string | null;
            /** Protocol Fingerprint */
            protocol_fingerprint: string;
        };
        /** ImportRequest */
        ImportRequest: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
        };
        /** NodeItem */
        NodeItem: {
            /** Key */
            key: string;
            /** Pointer */
            pointer: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "object" | "array" | "string" | "value";
            /** Preview */
            preview: string;
            /** Expandable */
            expandable: boolean;
            /** Total */
            total?: number | null;
        };
        /** NodePage */
        NodePage: {
            /** Session Id */
            session_id: string;
            /** Revision */
            revision: number;
            /** Artifact Id */
            artifact_id: string;
            /** Fingerprint */
            fingerprint?: string | null;
            /** Pointer */
            pointer: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "object" | "array" | "string" | "value";
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Items */
            items?: components["schemas"]["NodeItem"][];
            /** Text */
            text?: string | null;
            /** Value */
            value?: string | number | boolean | null;
        };
        /** Operation */
        Operation: {
            /** Operation Id */
            operation_id: string;
            /** Request Id */
            request_id: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "interrupted";
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            result?: components["schemas"]["OperationResult"] | null;
            error?: components["schemas"]["PublicError"] | null;
        };
        /** OperationList */
        OperationList: {
            /** Items */
            items: components["schemas"]["Operation"][];
        };
        /** OperationResult */
        OperationResult: {
            /** Session Id */
            session_id?: string | null;
            /** Revision */
            revision?: number | null;
        };
        /** Preview */
        Preview: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: unknown[][];
        };
        /** ProbeRequest */
        ProbeRequest: {
            credentials?: components["schemas"]["Credentials"];
        };
        /** ProbeResponse */
        ProbeResponse: {
            /** Connected */
            connected: boolean;
            /** Message */
            message: string;
        };
        /** ProtocolView */
        ProtocolView: {
            /** Session Id */
            session_id: string;
            /** Revision */
            revision: number;
            /** Summary */
            summary: string;
            /** Feedback */
            feedback: string;
            /** Columns */
            columns: components["schemas"]["Column"][];
            preview: components["schemas"]["Preview"];
            /** Protocol Fingerprint */
            protocol_fingerprint?: string | null;
            /** Repeat Count */
            repeat_count?: number | null;
            /** Accepted */
            accepted?: boolean | null;
            /** Evidence Options */
            evidence_options?: components["schemas"]["EvidenceOption"][];
        };
        /** PublicError */
        PublicError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Fields */
            fields?: {
                [key: string]: string;
            };
            /** Latest Revision */
            latest_revision?: number | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Receipt Saved
             * @default false
             */
            receipt_saved: boolean;
        };
        /** RAGStatus */
        RAGStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "preparing" | "ready" | "error";
            /** Message */
            message: string;
            /** Snapshot */
            snapshot?: string | null;
        };
        /** SectionPage */
        SectionPage: {
            /** Session Id */
            session_id: string;
            /** Revision */
            revision: number;
            /** Section */
            section: string;
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
        };
        /** TaskSummary */
        TaskSummary: {
            /** Session Id */
            session_id: string;
            /** Revision */
            revision: number;
            /** Status */
            status: string;
            /** Read Only */
            read_only: boolean;
            /** Task */
            task: {
                [key: string]: unknown;
            };
            workspace: components["schemas"]["Workspace"];
            /** Input Contract */
            input_contract: {
                [key: string]: unknown;
            };
            /** Pending Actions */
            pending_actions: {
                [key: string]: unknown;
            }[];
            /** Rag Snapshot */
            rag_snapshot?: string | null;
            /** Registered Case Id */
            registered_case_id?: string | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** File Id */
            file_id: string;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
        };
        /** Workspace */
        Workspace: {
            /** Stage */
            stage: number;
            /** Title */
            title: string;
            /** Explanation */
            explanation: string;
            /** Action */
            action: string;
            /** Action Title */
            action_title: string;
            /** Action Help */
            action_help: string;
            /** Actionable */
            actionable: boolean;
            /** Advanced */
            advanced: boolean;
            /** Result Visible */
            result_visible: boolean;
            /** Task Summary */
            task_summary: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    configuration_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    probe_api_v1_config_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    doctor_api_v1_config_doctor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cases_api_v1_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseList"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    default_draft_api_v1_drafts_default_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validate_draft_api_v1_drafts_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftValidationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_history_api_v1_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    action_api_v1_tasks__task_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    operation_api_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    task_operations_api_v1_tasks__task_id__operations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationList"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_api_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validate_artifact_api_v1_artifacts_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactValidationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    artifacts_api_v1_tasks__task_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactCatalog"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    node_api_v1_tasks__task_id__artifacts__artifact_id__node_get: {
        parameters: {
            query?: {
                pointer?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                task_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    section_page_api_v1_tasks__task_id__sections__section__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                task_id: string;
                section: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    protocol_api_v1_tasks__task_id__protocol_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    evaluations_api_v1_tasks__task_id__evaluations_get: {
        parameters: {
            query?: {
                selection?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationsView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    curves_api_v1_tasks__task_id__curves_get: {
        parameters: {
            query: {
                selection: string;
                signal: string;
                start?: number | null;
                end?: number | null;
                control?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurveView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    evidence_curves_api_v1_tasks__task_id__evidence_curves_get: {
        parameters: {
            query: {
                selection: string;
                signal: string;
                start?: number | null;
                end?: number | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceCurveView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_api_v1_tasks__task_id__downloads__kind__get: {
        parameters: {
            query?: {
                artifact_id?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
