function modelPath=build_model(caseDir)
%BUILD_MODEL Rebuild a local model from verified native Simulink block types.
root=fileparts(fileparts(mfilename('fullpath'))); addpath(root);
config=jsondecode(fileread(fullfile(caseDir,'case_config.json')));
name=config.model_name; folder=fullfile(caseDir,'model');
if ~isfolder(folder), mkdir(folder); end
modelPath=fullfile(folder,[name,'.slx']);
if bdIsLoaded(name)
    assert(strcmp(get_param(name,'Dirty'),'off'),'cfdcSim:UnsavedModel', ...
        'Save or close the edited model before rebuilding: %s',name);
    close_system(name,0);
end
new_system(name);
set_param(name,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','cfdc_dt','StopTime','20','ReturnWorkspaceOutputs','on', ...
    'SaveTime','on','SignalLogging','on');
workspace=get_param(name,'ModelWorkspace');
workspace.assignin('cfdc_dt',0.02); workspace.assignin('cfdc_run_key',['preview_',name]);
workspace.assignin('cfdc_bounds',[-1,1]);
% Positions and block types were read back from the toolkit-checked prototype.
add_block('built-in/Inport',[name,'/Excitation'],'Port','1','Interpolate','off','Position',[35,253,65,267]);
add_block('built-in/Inport',[name,'/Disturbance'],'Port','2','Interpolate','off','Position',[225,103,255,117]);
add_block('built-in/M-S-Function',[name,'/FrozenController'], ...
    'Parameters','cfdc_run_key,cfdc_dt','FunctionName','cfdc_controller_block','Position',[120,236,175,269]);
add_block('built-in/Saturate',[name,'/ActuatorLimits'], ...
    'LowerLimit','cfdc_bounds(1)','UpperLimit','cfdc_bounds(2)','Position',[235,165,265,195]);
add_block('built-in/Sum',[name,'/AppliedInput'],'Inputs','++','Position',[335,87,365,118]);
add_block('built-in/M-S-Function',[name,'/StateSpacePlant'], ...
    'Parameters','cfdc_run_key,cfdc_dt','FunctionName','cfdc_plant_block','Position',[410,89,465,121]);
add_block('built-in/Mux',[name,'/SampleRecord'],'Inputs','8','Position',[530,117,535,318]);
add_block('built-in/ToWorkspace',[name,'/Recorder'],'VariableName','cfdc_record', ...
    'SaveFormat','Timeseries','MaxDataPoints','inf','Position',[590,205,680,235]);
add_block('built-in/Scope',[name,'/ExperimentScope'],'Position',[620,289,650,321]);
add_block('built-in/Stop',[name,'/StopCondition'],'Position',[235,302,270,338]);
connections={ ...
    'Excitation/1','FrozenController/2'; 'StateSpacePlant/1','FrozenController/1'; ...
    'FrozenController/1','ActuatorLimits/1'; 'ActuatorLimits/1','AppliedInput/1'; ...
    'Disturbance/1','AppliedInput/2'; 'AppliedInput/1','StateSpacePlant/1'; ...
    'StateSpacePlant/1','SampleRecord/1'; 'FrozenController/2','SampleRecord/2'; ...
    'ActuatorLimits/1','SampleRecord/3'; 'FrozenController/1','SampleRecord/4'; ...
    'FrozenController/3','SampleRecord/5'; 'FrozenController/4','SampleRecord/6'; ...
    'FrozenController/5','SampleRecord/7'; 'FrozenController/6','SampleRecord/8'; ...
    'FrozenController/6','StopCondition/1'; 'SampleRecord/1','Recorder/1'; ...
    'SampleRecord/1','ExperimentScope/1'};
for i=1:size(connections,1), add_line(name,connections{i,1},connections{i,2},'autorouting','on'); end
set_param(name,'Description',sprintf('CFDC external software apparatus: %s. Run setup_case before opening; use downloaded packets for evidence.',config.case_id));
save_system(name,modelPath);
end
