const labels: Record<string, string> = {
  queued: "等待执行",
  running: "执行中",
  completed: "已完成",
  failed: "失败",
  interrupted: "已中断",
  intake: "待确认任务",
  diagnostic: "结构诊断中",
  awaiting_evidence: "等待补充证据",
  protocol_ready: "协议已就绪",
  awaiting_operator_report: "等待操作检查",
  awaiting_provider: "等待实验",
  route_ready: "路线已确定",
  controller_pending: "等待控制器",
  controller_candidate_ready: "候选方案已生成",
  controller_qualified: "资格检查已通过",
  controller_ready: "方案已冻结",
  evaluation_recorded_pending_replay: "等待评价复核",
  tuning_eligible: "可进行有界调优",
  awaiting_confirmation: "等待独立确认",
  performance_met: "任务已结束（查看结论）",
  capability_gap: "当前能力不足",
  cancelled: "任务已取消",
  known: "已知",
  unknown: "未知",
  needs_clarification: "需要澄清",
  ok: "通过",
  warning: "需注意",
  error: "失败",
};
export const statusLabel = (status: string) => labels[status] ?? status;
